version: '2.3'

services:
  fortress-focal-dev:
    image: isabelleysseric/ignition:fortress-focal
    container_name: nvidia-fortress-focal
    runtime: nvidia
    network_mode: "host"
    privileged: true
    group_add:
      - video
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ign:/root/.ignition
    working_dir: /usr/share/ignition/ignition-gazebo6/worlds
    command: /bin/sh -c "ign gazebo -v4 tunnel.sdf"

volumes:
  ign:
