version: '2.3'

services:
  fortress-focal-dev:
    image: isabelleysseric/ignition:fortress-focal
    container_name: intel-fortress-focal
    network_mode: "host"
    privileged: true
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ign:/root/.ignition
    devices:
      - /dev/dri:/dev/dri
    working_dir: /usr/share/ignition/ignition-gazebo6/worlds
    command: /bin/sh -c "ign gazebo -v4 tunnel.sdf"

volumes:
  ign:
